services:
  app:
    build: .
    container_name: inventory-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inventory
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - inventory-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inventory-network
    restart: unless-stopped

networks:
  inventory-network:
    driver: bridge

volumes:
  postgres-data: